### ISSUE TITLE
This is not the latest version

### ISSUE THREAD

**Issue by Larceniii** [ruhanirabin/WP-Optimize#57]
There is a security update on wordpress website that is not here.  I removed the plugin for safety.

**Comment by ruhanirabin** [comment]
Hello maybe you were looking at dev branch? the master branch is updated here. No worries, mainly WP.org strangled me to do the update quickly check header of this file (https://github.com/ruhanirabin/WP-Optimize/blob/master/wp-optimize.php)

**Comment by Larceniii** [comment]
Yeah maybe that was the problem! I thought I switched to master. Thanks for speedy response!
