### ISSUE TITLE
Uninstall leads to undefined variable/non-object errors

### ISSUE THREAD

**Issue by jmccall75** [ruhanirabin/WP-Optimize#58]
When I uninstall WP-optimize I get errors for all my custom taxonomies throughout the site. For example: 

Notice: Undefined variable: post in ...\wp-content\themes\ecotone-2015\woocommerce\woo-functions.php on line 118

Notice: Trying to get property of non-object in ...\wp-content\themes\ecotone-2015\woocommerce\woo-functions.php on line 118

Everthing works perfectly well with the plugin installed (and before I ever used the plugin) but falls apart if I uninstals. Any ideas?

**Comment by ruhanirabin** [comment]
It does not modify any core properties of wordpress. It is possible that
you might have installed something new after installing this plugin that
essentially depending on wpo. Which, I highly doubt it. Because WPO does
not modify system details nor uses things that can make others depend on
it. Basically standalone.

You should clear out browser cache etc.

Anyways. Your theme might have issues too.

On Wednesday, April 1, 2015, jmccall75 <notifications@github.com> wrote:

> When I uninstall WP-optimize I get errors for all my custom taxonomies
> throughout the site. For example:
>
> Notice: Undefined variable: post in
> ...\wp-content\themes\ecotone-2015\woocommerce\woo-functions.php on line 118
>
> Notice: Trying to get property of non-object in
> ...\wp-content\themes\ecotone-2015\woocommerce\woo-functions.php on line 118
>
> Everthing works perfectly well with the plugin installed (and before I
> ever used the plugin) but falls apart if I uninstals. Any ideas?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ruhanirabin/WP-Optimize/issues/58>.
>


-- 
Sent from iPhone

**Comment by jmccall75** [comment]
But why would these problems only occur when I uninstall WPO? I don't get any errors otherwise (even with debug turned on).

**Comment by jmccall75** [comment]
And I get the same errors on local and development server. But again, only with WPO deactivited.

**Comment by jmccall75** [comment]
Does the plugin turn off debugging?

**Comment by ruhanirabin** [comment]
It does not turn off debugging in the latest version
On April 2, 2015 at 5:07:53 AM, jmccall75 (notifications@github.com) wrote:

Does the plugin turn off debugging?

**Comment by jmccall75** [comment]
I have version 1.8.9.10. It seems to interfere with debugging in some way. All the issues that appeared when I uinstalled were theme related, but re-installing the plugin prevents the debug notices.

**Comment by jmccall75** [comment]
This is the problem, from line 5 of wp-optimize-main.php: 

https://github.com/ruhanirabin/WP-Optimize/issues/58#issuecomment-88695717

`error_reporting( error_reporting() & ~E_NOTICE`

**Comment by Otto42** [comment]
@ruhanirabin When you removed the two instances of the code that disabled the NOTICE messages via error_reporting two weeks ago (for the 1.8.9.9 release), you missed one:

See here: https://plugins.svn.wordpress.org/wp-optimize/trunk/wp-optimize.php

Please remove that as well, and release a new version in the WordPress.org plugin directory. Plugins that aren't specifically related to debugging should not be adjusting the global error_reporting settings. It leads to issues like this.

**Comment by ruhanirabin** [comment]
Yes it's on queue for next release.

On Friday, April 3, 2015, Samuel Wood <notifications@github.com> wrote:

> @ruhanirabin <https://github.com/ruhanirabin> When you removed the two
> instances of the code that disabled the NOTICE messages via error_reporting
> two weeks ago (for the 1.8.9.9 release), you missed one:
>
> See here:
> https://plugins.svn.wordpress.org/wp-optimize/trunk/wp-optimize.php
>
> Please remove that as well, and release a new version in the WordPress.org
> plugin directory. Plugins that aren't specifically related to debugging
> should not be adjusting the global error_reporting settings. It leads to
> issues like this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ruhanirabin/WP-Optimize/issues/58#issuecomment-89061092>
> .
>


-- 
Sent from iPhone
