### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by christophherr** [ruhanirabin/WP-Optimize#68]
Hi,

I just translated the plugin on translate.wordpress.org and found a few typos. 
I will submit a PR for those.

Also wondering if it would make sense to update the call for translators to sign up at translate.wordpress.org?

**Comment by ruhanirabin** [comment]
Hi @christophherr yes i agree translators should go to the WP translator repository for this. Did you pull the latest code from dev and commit ? That would be great :)

**Comment by christophherr** [comment]
Hi @ruhanirabin yes, forked today and committed right after :)
