### ISSUE TITLE
found more errors closed tags

### ISSUE THREAD

**Issue by kniebremser** [ruhanirabin/WP-Optimize#73]
in wp-optimize-credits.php line 10 is open div --> closed div missed   see #77 
in wp-optimize-settings.php line 124 is open div --> closed div missed see #78
in wp-optimize-main.php line 151 is open form --> closed form missed see in #79

in wp-optimize-credits.php line 23 is:  alt="PayPal ï¿½ The safer, easier way to pay online."
the signs behind paypal is ????  see #77

**Comment by ruhanirabin** [comment]
Hi did you manage to fix the above divs?

**Comment by kniebremser** [comment]
all closed tags errors are fixed in #77 , #78 and #79.
Other small html bugs were also eliminated (e.g. unused tags)
unique code formatting for all 3 files.
Tested with Firefox everything is fine. No changes in the functions.

**Comment by kniebremser** [comment]
is all fixed
