### ISSUE TITLE
changing the translations on wordpress translations

### ISSUE THREAD

**Issue by kniebremser** [ruhanirabin/WP-Optimize#85]
WordPress has now switched own translation pages sharp.
Please refer:
https://translate.wordpress.org/projects/wp-plugins/wp-optimize
Thus, the translations are superfluous within the plugin.
The indications and the side on http://wp-managed.com/projects/wp-optimize can be removed.

**Comment by ruhanirabin** [comment]
i have updated the dev version according these changes
